apiVersion: v1
entries:
  scraperr:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-05-13T23:04:11.926871207Z"
    description: A Helm chart for Kubernetes
    digest: 796e3a89a2c1924820c10fc399a5f4b2506e3de9e41fec467b8c1564e1fd860f
    name: scraperr
    type: application
    urls:
    - https://jaypyles.github.io/helm/charts/scraperr/scraperr-1.0.12.tgz
    version: 1.0.12
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-05-13T23:04:11.9265947Z"
    description: A Helm chart for Kubernetes
    digest: 9b59c2be3d89ec0ef1ef2fe05773f4f74fda6cc89a9724b930d50a1c3859fa62
    name: scraperr
    type: application
    urls:
    - https://jaypyles.github.io/helm/charts/scraperr/scraperr-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-05-13T23:04:11.926314777Z"
    description: A Helm chart for Kubernetes
    digest: c243cf6cc0a2f1c7ab738d930f94c9d45c873138984aa3a8dc0be86411af35d6
    name: scraperr
    type: application
    urls:
    - https://jaypyles.github.io/helm/charts/scraperr/scraperr-0.0.1.tgz
    version: 0.0.1
generated: "2025-05-13T23:04:11.925854557Z"
