apiVersion: v1
entries:
  scraperr:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-05-16T19:05:35.730521606Z"
    description: A Helm chart for Kubernetes
    digest: 9bcdd223ede6e82521a15099b50484d6c30fede32015cdab98923bbfefd60036
    name: scraperr
    type: application
    urls:
    - https://jaypyles.github.io/helm/charts/scraperr/scraperr-1.0.13.tgz
    version: 1.0.13
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-05-16T19:05:35.730219884Z"
    description: A Helm chart for Kubernetes
    digest: d92e24c8564f8a28bff00289890c490591198754905e4d9813b3db28cb5aa6dd
    name: scraperr
    type: application
    urls:
    - https://jaypyles.github.io/helm/charts/scraperr/scraperr-1.0.12.tgz
    version: 1.0.12
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-05-16T19:05:35.729913813Z"
    description: A Helm chart for Kubernetes
    digest: 9b59c2be3d89ec0ef1ef2fe05773f4f74fda6cc89a9724b930d50a1c3859fa62
    name: scraperr
    type: application
    urls:
    - https://jaypyles.github.io/helm/charts/scraperr/scraperr-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-05-16T19:05:35.729626509Z"
    description: A Helm chart for Kubernetes
    digest: c243cf6cc0a2f1c7ab738d930f94c9d45c873138984aa3a8dc0be86411af35d6
    name: scraperr
    type: application
    urls:
    - https://jaypyles.github.io/helm/charts/scraperr/scraperr-0.0.1.tgz
    version: 0.0.1
generated: "2025-05-16T19:05:35.729165459Z"
