apiVersion: v1
entries:
  saas-template:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-06-22T20:59:45.998118196Z"
    description: Helm chart for the saas-template
    digest: e28d4460004f3c5e034c084e7e61b0048f32a5db8f634a9a773f3cf006392d93
    name: saas-template
    type: application
    urls:
    - https://jaypyles.github.io/helm/charts/saas-webapp-template/saas-template-1.0.0.tgz
    version: 1.0.0
generated: "2025-06-22T20:59:45.997691393Z"
